name:         bitcoin-payment-protocol
version:      '0.1.0.0'
synopsis:     Bitcoin payment protocol (BIP 70/71)
author:       Rune K. Svendsen
maintainer:   runesvend@gmail.com
license:      OtherLicense
license-file: LICENSE

default-extensions:
- OverloadedStrings
- MultiParamTypeClasses
- TypeOperators
- DataKinds
- FlexibleContexts
- RecordWildCards

### Temporarily disable, because of dependency on haskell-src-exts == 1.17.*
## Generate 'Proto.PayReq' from 'protobuf/pay_req.proto'
#build-type:         Custom
#extra-source-files: protobuf/pay_req.proto

dependencies:
- base            >=4.7 && <5
- proto-lens      >=0.1 && <0.2
- haskoin-core    >=0.4 && <0.5
- time
- servant
- servant-server
- servant-client
- wai
- warp
- http-media
- bytestring
- text
- string-conversions
- cereal
- containers
- data-default-class
- lens-family


ghc-options: -W

library:
  source-dirs:      src
  exposed-modules:
    - PayProto
    - PayProto.API
    - PayProto.Util
    - PayProto.Gen.PayReq
#  other-modules:


executables:
  payproto-test:
    source-dirs: test
    main: Test.Main
    dependencies:
      - bitcoin-payment-protocol
